version: '3.9'

services:
  db:
    image: redis:7.2.4
    restart: unless-stopped
    ports:
      - "6379:6379"
  redis-commander:
    image: rediscommander/redis-commander
    restart: unless-stopped
    container_name: redis_commander
    ports:
      - "8080:8081"
    depends_on:
      - db
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=password
      - HTTP_USER=username
      - HTTP_PASSWORD=password
